# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
     
     
      - name: GetLatestTweet
        run: |
          sudo apt-get install -y jq
          latestTweet=$(curl -s --request GET \
           --url 'https://api.twitter.com/2/tweets/search/recent?query=conversation_id:1320182216903872512&tweet.fields=in_reply_to_user_id,author_id,created_at,conversation_id' \
           --header "Authorization: Bearer $BEARER_TOKEN" | jq '.meta.newest_id as $new | .data | map(select(.id==$new ))[0].id | tonumber')
     
     #caching would be nice, but they evict after 7 days...
     
     #I would prefer to use the ubuntu packages, but github actions preinstall v4, which is incompatible with the aptitiude versions
      - name: RTest
        if: ${{ false }}    
        run: |
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev
          Rscript -e 'install.packages("tidyverse")'
          Rscript 'covid cubic.R'

#      - name: debug
#        run: |
#          echo "${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}"
#          Rscript -e '.libPaths()'
#          echo "${{env.R_LIBS_USER }}"


 #     # Runs a set of commands using the runners shell
 #     - name: Run a multi-line script
 #       run: |
 #         echo "Add other actions to build," >> test.txt
 #         echo "test, and deploy your project." >> test.txt
          
          
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            test.txt
            out.png
          
