# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
     
     #I would prefer to use the ubuntu packages, but github actions preinstall v4, which is incompatible with the aptitiude versions
      - name: RTest    
        run: |
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev
          Rscript -e 'install.packages("tidyverse")'
          Rscript 'covid cubic.R'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build," >> test.txt
          echo "test, and deploy your project." >> test.txt
          
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: test.txt
